export const disordersStr: string[] = ["Alcohol Adiction",
                                    "Anorexia",
                                    "Antisocial",
                                    "Anxiety",
                                    "Bipolar",
                                    "Bulimia",
                                    "Dependent",
                                    "Depression",
                                    "Kleptomaniac",
                                    "Nicotine",
                                    "Obsessive",
                                    "Panic",
                                    "Paranoid",
                                    "Post-traumatic stress",
                                    "Programmer",
                                    "Tester"];